### ISSUE TITLE
unhandled exception of type 'System.NotImplementedException' Unknown wire type: 7

### ISSUE THREAD

**Issue by dancri77** [hultqvist/ProtoBuf#24]
I am trying to deserialise a kura mqtt package and get 'System.NotImplementedException' Unknown wire type: 7.
The kura proto file I used to generate the .cs files is here: https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.cloud/src/main/protobuf/kurapayload.proto
the message to be decode is this one, string of bytes value: "31,139,8,0,0,0,0,0,0,0,227,248,186,233,237,179,77,154,135,118,48,201,112,9,151,164,230,22,164,22,37,150,148,22,165,186,86,148,164,22,229,37,230,8,48,170,50,48,44,112,192,144,247,204,67,150,119,4,202,75,115,9,161,232,207,72,44,45,46,1,75,127,0,73,243,115,113,166,22,21,229,23,57,231,167,164,10,48,27,48,0,0,49,79,132,184,121,0,0,0"
Can you advise what the fix for this is?

Thanks,
Dan

   at SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(Stream stream, Key key) in c:\Development\GIT\MZP\MZP-NET\MultiZonePlayer\ThirdParty\ProtocolParser.cs:line 446
   at Kuradatatypes.KuraPayload.Deserialize(Stream stream, KuraPayload instance) in c:\Development\GIT\MZP\MZP-NET\MultiZonePlayer\ThirdParty\kurapayload.Serializer.cs:line 105
   at Kuradatatypes.KuraPayload.Deserialize(Byte[] buffer) in c:\Development\GIT\MZP\MZP-NET\MultiZonePlayer\ThirdParty\kurapayload.Serializer.cs:line 48
   at MultiZonePlayer.Test.client_MqttMsgPublishReceived(Object sender, MqttMsgPublishEventArgs e) in c:\Development\GIT\MZP\MZP-NET\MultiZonePlayer\Test.cs:line 196
   at uPLibrary.Networking.M2Mqtt.MqttClient.OnMqttMsgPublishReceived(MqttMsgPublish publish) in c:\Development\GIT\MZP\MZP-NET\M2Mqtt\MqttClient.cs:line 875
   at uPLibrary.Networking.M2Mqtt.MqttClient.DispatchEventThread() in c:\Development\GIT\MZP\MZP-NET\M2Mqtt\MqttClient.cs:line 1704
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by hultqvist** [comment]
Try this:

            byte[] buffer = new byte[] { 31, 139,...
            var kura = Kuradatatypes.KuraPayload.Deserialize(buffer);

The exception actually happens at the first byte: 31
31 is decoded into Field = 3, WireType=7

It was not clear which of the messages that I should use to decode the bytes but in the end it does not matter because 7 is not a valid WireType.

Make sure this is really the start of the encoded message.

You can also create a message with the same content, serialize to bytes and compare the results with your byte stream above.

**Comment by dancri77** [comment]
Thanks Peter for the fast reply.
I will look more into this, maybe the MQTT message get's corrupted at sent or when is received by Apache Apollo broker I use.

**Comment by hultqvist** [comment]
Protocol Buffer is only one part of a protocol there may be other leading data that is out of scope for Protocol Buffer.
Let me know if you find anything interesting.

Good Luck
